### ISSUE TITLE
Camp Harmony: Campership calculation issues

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#421]
You can click the "down" arrow and get a negative number in campership box -- number shouldn't go lower than zero.

If you enter a number that's too high and delete it, error message says "Campership request is a required property." Can we change this message to "Please enter a number between 0-$300"

Campership discount is 50% of the early bird economy rate. Maximum campership discount is $300.  If I choose semi-private full camp, it's $960.  I can request $480 campership and get it.   Total should be $660 due to the $300 limit. 

If I sign up for 1 day early-bird Semi-private ($197) and ask for $98.50 (or more) campership, the total shown is $98.50. But it should be $126 because 1/2 the one-day economy rate is $71.

**Comment by willfulbard** [comment]
In the future, please put these as three separate issues.

**Comment by willfulbard** [comment]
sub issue 1: I can't change that, but it does indicate an error if you try to use that number

sub issue 2: I can't change these error messages right now, I will add this as a future feature to add

sub issue 3: This will be fixed in the next test cycle

sub issue 4: this will be fixed in the next test cycle, I missed the "economy rate" part of the formula (this camp is complicated)

**Comment by bloomingbooks** [comment]
got it. Ok to all.
